---
title: "Categorical MSM"
author: "Ryan_Gan"
date: "June 7, 2017"
output: html_document
---

```{r libraries, message=F}
library(tidyverse)
library(broom)
library(contrast)
```

## Simulated dataset

Simulating a simple continous distribution and a linear relationship with binary outcome which I'll then break in to an ordinal catogory by tertiles. No confounding yet.

```{r sim data}
n <- 500
set.seed(333)

# create normal distribution of x with mean of 16 and sd of 4
sim_data <- data_frame(x = rnorm(n, 16, 4)) %>% 
  # simulate y data with linear logit relationship to x
  mutate(y = rbinom(n, 1, 1/(1+exp(-(-1+0.10*x)))),
         # split in to three categories
         x_cat = ifelse(x < quantile(x,1/3), 1,
                 ifelse(x > quantile(x,2/3), 3, 2)),
         # dummy variable
         x1 = ifelse(x_cat == 1, 1, 0),
         x2 = ifelse(x_cat == 2, 1, 0),
         x3 = ifelse(x_cat == 3, 1, 0),
         x2_3 = ifelse(x_cat == 2 | x_cat == 3, 1, 0))
```

  
```{r standard estimates}
# check density plots of x category given x
ggplot(sim_data, aes(x=x, fill=as.factor(x_cat))) +
  geom_density(alpha = 0.5)



# estimates good enough for example
mod1 <- glm(y~x, sim_data, family="binomial"(link="logit"))
mod1$coefficients

# plot predicted probability of the linear funciton
pr_y_x <- predict(mod1, sim_data, type="response")

# plot of predicted probability of continous variable
ggplot(sim_data, aes(x=x, y=pr_y_x)) +
  geom_point()

```

Standard analysis asking what the risk difference is strata to strata

```{r risk difference}
# 2x3 table
y_x <- xtabs(~x_cat+y, sim_data)
pr_yx <- prop.table(y_x, 1)
pr_yx
# difference in risk from strata 2 to 1
pr_yx[2,2] - pr_yx[1,2]
# difference in risk from strata 3 to 1
pr_yx[3,2] - pr_yx[1,2]
# difference in risk from strata 3 to 2
pr_yx[3,2] - pr_yx[2,2]

# estimate risk difference using binomial, link=identity for appropriate SE
risk_diff_mod <- glm(y~x2+x3, sim_data, family="binomial"(link="identity"))
summary(risk_diff_mod)

# comparing difference in x3 to x2
risk_diff_mod2 <- glm(y~x3+x1, sim_data, family="binomial"(link="identity"))
summary(risk_diff_mod2)
# difference between groups 3 and 2 as well
# now what if we combine groups x 3 and 2 together and compared against 1

risk_diff_mod3 <- glm(y~x2_3, sim_data,family="binomial"(link="identity"))
summary(risk_diff_mod3)


```
