---
title: "Mediation"
author: "Ryan Gan"
date: "6/7/2017"
output: html_document
---



```{r load libraries, warning=F, message=F}
library(broom) # for easy conversion of model results to dataframes
library(tidyverse) # data wrangling
```

Simulating a mediated dataframe where x -> m -> y, where x perfectly predicts m.

```{r sim mediated data}
# set df observations
n <- 500
# set seed
seed(303)

# making continous x
sim_data <- data_frame(x = rnorm(n, 6, 0.5)) %>% 
  # simulate where x perfectly predits m
  mutate(m = x, 
  # simulate a protect effect between x and y
         y = rbinom(n, 1, 1/(1+exp(-(3.5+-0.6*m)))))
```

First step is to establish the relationship between x and y

```{r xy association}
summary(sim_data)
# check mod estimates
# this is referered to the direct effect
mod <- tidy((glm(y~x, sim_data, family="binomial"(link="logit"))))
mod
# OR
round(exp(mod[2,2]),3)
# 95 CI
round(exp(c(mod[2,2]-1.96*mod[2,3], mod[2,2]+1.96*mod[2,3])),3)
```

Second step is establishing x -> m, and m -> y relationship.

```{r xm my association}
xm_mod <- tidy(glm(m~x, sim_data, family = "gaussian"(link="identity")))
# perfect relationship 
xm_mod

# my mod
my_mod <- tidy(glm(y~m, sim_data, family="binomial"(link="logit")))
my_mod

# OR
round(exp(my_mod[2,2]),3)
# 95 CI
round(exp(c(my_mod[2,2]-1.96*my_mod[2,3], my_mod[2,2]+1.96*my_mod[2,3])),3)
```

Now that each path of the DAG has been confirmed, we calculate the controled direct effect.

```{r cde}

cde_mod <- tidy(glm(y~ x + m, sim_data, family="binomial"(link="logit")))  

cde_mod
```
